### PR TITLE
Remove notifications as we don't reload

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done

Removed the notifications as we no longer reload the page
Improved the experience at the end by triggering a page reload

## QA
- Go to the application review
- Review some people and see it behaviours as expected
- Quickly reject the last candidate and see that it reloads and shows the end screen.
- **Known issue that the numbers are not correct** (_give me a break_) 

Fixes https://github.com/canonical/greenhouse-browser-scripts/issues/17
Fixes https://github.com/canonical/greenhouse-browser-scripts/issues/7

### CODE REVIEW

**Comment by anthonydillon** [comment]
@Lukewh mind reviewing and QAing this one for me?

**Review by Lukewh — APPROVED** [review]
:+1: LGTM - I'll properly QA the end screen thing when we get to the end of the reviews :D

**Comment by Lukewh** [comment]
The summary seems to be 0 across the board 
image

**Comment by anthonydillon** [comment]
Yeah, I assume you rejected them all. I have not worked out how to effect to global counts be this PR now ends at the right point.

**Comment by anthonydillon** [comment]
I think as a follow up I'll test using the UI entirely instead of the API but making the modal invisible when interacting with it. This should fix the entire process but there might be dragons.

**Pull request merged**
